create table Customers(
CustomersID INT NOT NULL,
FirstName VARCHAR2(30),
LastName VARCHAR2(30)
);

INSERT INTO CUSTOMERS (CUSTOMERSID, FIRSTNAME, LASTNAME)
VALUES (1, 'Sara', 'Davis');

INSERT INTO CUSTOMERS (CUSTOMERSID, FIRSTNAME, LASTNAME)
VALUES (2, 'Rumi', 'Shah');

INSERT INTO CUSTOMERS (CUSTOMERSID, FIRSTNAME, LASTNAME)
VALUES (3, 'Paul', 'Johnson');

INSERT INTO CUSTOMERS (CUSTOMERSID, FIRSTNAME, LASTNAME)
VALUES (4, 'Samuel', 'Martinez');